Repository vyperlang/vyper, pull requests merged in 2023-12, with the labels that each got.

#3685 Refactor ctx.add_instruction() and friends
  tests/unit/compiler/venom/test_duplicate_operands.py
  tests/unit/compiler/venom/test_multi_entry_block.py
  vyper/venom/analysis.py
  vyper/venom/basicblock.py
  vyper/venom/function.py
  vyper/venom/ir_node_to_venom.py
  vyper/venom/passes/normalization.py
  vyper/venom/venom_to_assembly.py
Labels: Refactor

#3702 fix: type annotation of helper function
  vyper/venom/ir_node_to_venom.py
Labels: bug - codegen

#3687 feat: Implement target constrained venom jump instruction
  tests/unit/ast/test_pre_parser.py
  tests/unit/compiler/venom/test_multi_entry_block.py
  vyper/cli/vyper_compile.py
  vyper/codegen/core.py
  vyper/codegen/module.py
  vyper/compiler/__init__.py
  vyper/compiler/output.py
  vyper/compiler/phases.py
  vyper/compiler/settings.py
  vyper/ir/compile_ir.py
  vyper/utils.py
  vyper/venom/analysis.py
  vyper/venom/basicblock.py
  vyper/venom/function.py
  vyper/venom/ir_node_to_venom.py
  vyper/venom/passes/normalization.py
  vyper/venom/venom_to_assembly.py
Labels: Feature

#3711 docs: clarify `address.codehash` for empty account
  docs/types.rst
Labels: documentation
