Repository vyperlang/vyper, pull requests merged in 2024-12, with the labels that each got.

#4386 chore[ci]: enable Python `3.13` tests
  .github/workflows/test.yml
  setup.py
Labels: enhancement

#4286 fix[tool]: add missing user errors to error map
  tests/unit/compiler/test_source_map.py
  vyper/codegen/ir_node.py
Labels: release - must

#4343 fix[ux]: add missing filename to syntax exceptions
  tests/functional/syntax/exceptions/test_vyper_exception_pos.py
  tests/unit/ast/test_natspec.py
  tests/unit/ast/test_pre_parser.py
  tests/unit/cli/vyper_json/test_compile_json.py
  vyper/ast/natspec.py
  vyper/ast/parse.py
  vyper/exceptions.py
Labels: release - must

#4268 fix[lang]: disallow absolute relative imports
  tests/functional/codegen/test_interfaces.py
  tests/functional/syntax/test_import.py
  tests/unit/cli/vyper_json/test_compile_json.py
  vyper/compiler/input_bundle.py
  vyper/semantics/analysis/imports.py
Labels: release - must

#4328 fix[tool]: add missing internal functions to metadata
  tests/unit/cli/vyper_json/test_output_selection.py
  vyper/compiler/output.py
Labels: release - must

#4290 feat[ux]: allow "compiling" `.vyi` files
  tests/functional/codegen/test_interfaces.py
  tests/unit/ast/test_ast_dict.py
  tests/unit/cli/vyper_compile/test_compile_files.py
  vyper/ast/nodes.py
  vyper/ast/nodes.pyi
  vyper/ast/parse.py
  vyper/compiler/__init__.py
  vyper/compiler/output.py
  vyper/compiler/phases.py
  vyper/semantics/analysis/module.py
  vyper/semantics/types/user.py
Labels: release - must

#4425 fix[stdlib]: fix `IERC4626` signatures
  .github/workflows/pull-request.yaml
  vyper/builtins/interfaces/IERC4626.vyi
Labels: release - must

#4338 fix[tool]: fix output formats for .vyz files
  tests/functional/venom/test_venom_repr.py
  tests/unit/cli/vyper_compile/test_compile_files.py
  tests/unit/cli/vyper_json/test_compile_json.py
  tests/unit/compiler/test_bytecode_runtime.py
  vyper/cli/vyper_compile.py
  vyper/cli/vyper_json.py
  vyper/compiler/phases.py
  vyper/compiler/settings.py
  vyper/ir/compile_ir.py
Labels: release - must

#4416 chore[docs]: `nonpayable` `internal` function behaviour
  docs/control-structures.rst
Labels: documentation

#4415 chore[docs]: abi function signature for default arguments
  docs/control-structures.rst
  docs/interfaces.rst
Labels: documentation
