Repository vyperlang/vyper, pull requests merged in 2024-11, with the labels that each got.

#4355 chore[docs]: add `method_id` to `abi_encode` signature
  docs/built-in-functions.rst
Labels: documentation

#4096 refactor[test]: add some sanity checks to `abi_decode` tests
  tests/functional/builtins/codegen/test_abi_decode.py
Labels: release - must

#4366 refactor[tool]: refactor `compile_from_zip()`
  vyper/cli/compile_archive.py
  vyper/compiler/__init__.py
  vyper/compiler/phases.py
Labels: release - must

#4090 feat[lang]: add `module.__at__()` to cast to interface
  docs/using-modules.rst
  tests/functional/codegen/modules/test_exports.py
  tests/functional/codegen/modules/test_interface_imports.py
  tests/functional/codegen/test_interfaces.py
  tests/functional/syntax/modules/test_deploy_visibility.py
  tests/functional/syntax/modules/test_exports.py
  tests/functional/syntax/test_interfaces.py
  vyper/codegen/expr.py
  vyper/compiler/output.py
  vyper/semantics/analysis/base.py
  vyper/semantics/analysis/module.py
  vyper/semantics/analysis/utils.py
  vyper/semantics/types/__init__.py
  vyper/semantics/types/base.py
  vyper/semantics/types/function.py
  vyper/semantics/types/module.py
Labels: release - must

#4321 fix[venom]: fix duplicate allocas
  vyper/builtins/functions.py
  vyper/codegen/context.py
  vyper/codegen/core.py
  vyper/venom/README.md
  vyper/venom/__init__.py
  vyper/venom/ir_node_to_venom.py
  vyper/venom/passes/__init__.py
  vyper/venom/passes/float_allocas.py
  vyper/venom/passes/sccp/sccp.py
Labels: venom

#4373 fix[venom]: add missing extcodesize+hash effects
  vyper/venom/effects.py
Labels: release - must
