Repository vyperlang/vyper, pull requests merged in 2025-06, with the labels that each got.

#4700 fix[lang]: disallow `@raw_return` in interfaces
  tests/functional/codegen/features/decorators/test_raw_return.py
  vyper/semantics/types/function.py
Labels: release - must

#4668 fix[tool]: add metadata for ctor functions
  tests/unit/cli/vyper_json/test_output_selection.py
  vyper/compiler/output.py
Labels: release - tentative

#4672 fix[tool]: fix invalid quotes in `-f cfg` output
  tests/unit/cli/vyper_json/test_compile_json.py
  vyper/venom/function.py
Labels: release - tentative

#4633 feat[tool]!: make `prague` the default evm version
  .github/workflows/test.yml
  docs/compiling-a-contract.rst
  setup.py
  tests/conftest.py
  tests/evm_backends/pyevm_env.py
  tests/unit/cli/vyper_json/test_get_settings.py
  tests/unit/compiler/test_opcodes.py
  vyper/evm/opcodes.py
Labels: enhancement, release - tentative

#4677 fix[parser]: generate unique nodes from python AST singletons
  tests/unit/ast/nodes/test_singletons.py
  vyper/ast/parse.py
Labels: release - tentative
